"""initial

Revision ID: 663e297881b8
Revises: 
Create Date: 2026-03-12 01:50:19.788315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '663e297881b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    op.alter_column('users', 'avatar',
               existing_type=postgresql.BYTEA(),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.BLOB(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=True)
    # ### end Alembic commands ###
